#!/bin/bash
# =============================================================================
# Urdu RTL Styler Setup Script v1.1.0
# =============================================================================
# Usage: ./setup.sh [OPTIONS]
#
# Options:
#   --font FONT         Primary Urdu font (default: "Noto Nastaliq Urdu")
#   --fallback FONTS    Fallback fonts, comma-separated
#   --source SOURCE     Font source: google or local (default: google)
#   --auto-config       Auto-update docusaurus.config.js with RTL settings
#   --scaffold          Create i18n/ur/ directory structure with sample content
#   --line-height N     Line height for Urdu text (default: 2.2)
#   -h, --help          Show this help message
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Default values
PRIMARY_FONT="Noto Nastaliq Urdu"
FALLBACK_FONTS="Jameel Noori Nastaleeq, Urdu Typesetting, serif"
FONT_SOURCE="google"
AUTO_CONFIG=false
SCAFFOLD=false
LINE_HEIGHT="2.2"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"

# =============================================================================
# Functions
# =============================================================================

show_help() {
    cat << 'EOF'
Urdu RTL Styler - Apply Urdu typography and RTL layout to Docusaurus

Usage: ./setup.sh [OPTIONS]

Options:
  --font FONT         Primary Urdu font (default: "Noto Nastaliq Urdu")
  --fallback FONTS    Fallback fonts, comma-separated
  --source SOURCE     Font source: google or local (default: google)
  --auto-config       Auto-update docusaurus.config.js with RTL settings
  --scaffold          Create i18n/ur/ directory structure with sample content
  --line-height N     Line height for Urdu text (default: 2.2)
  -h, --help          Show this help message

Examples:
  ./setup.sh                                    # Basic setup with defaults
  ./setup.sh --auto-config --scaffold           # Full automated setup
  ./setup.sh --font "Jameel Noori Nastaleeq" --source local
  ./setup.sh --line-height 2.4

EOF
}

log_info() { echo -e "${BLUE}ℹ${NC} $1"; }
log_success() { echo -e "${GREEN}✓${NC} $1"; }
log_warning() { echo -e "${YELLOW}⚠${NC} $1"; }
log_error() { echo -e "${RED}✗${NC} $1" >&2; }

# =============================================================================
# Parse Arguments
# =============================================================================

while [[ $# -gt 0 ]]; do
    case $1 in
        --font)
            PRIMARY_FONT="$2"
            shift 2
            ;;
        --fallback)
            FALLBACK_FONTS="$2"
            shift 2
            ;;
        --source)
            FONT_SOURCE="$2"
            shift 2
            ;;
        --auto-config)
            AUTO_CONFIG=true
            shift
            ;;
        --scaffold)
            SCAFFOLD=true
            shift
            ;;
        --line-height)
            LINE_HEIGHT="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# =============================================================================
# Main Setup
# =============================================================================

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎨 Urdu RTL Styler Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
log_info "Font: $PRIMARY_FONT"
log_info "Fallback: $FALLBACK_FONTS"
log_info "Source: $FONT_SOURCE"
log_info "Line Height: $LINE_HEIGHT"
echo ""

# =============================================================================
# 1. Create CSS with custom font settings
# =============================================================================

mkdir -p src/css

# Generate Google Fonts import URL (encode spaces)
FONT_URL_ENCODED=$(echo "$PRIMARY_FONT" | sed 's/ /+/g')
GOOGLE_IMPORT="@import url('https://fonts.googleapis.com/css2?family=${FONT_URL_ENCODED}:wght@400;500;600;700&display=swap');"

# Build font stack
FONT_STACK="'${PRIMARY_FONT}', ${FALLBACK_FONTS}"

# Create customized CSS
cat > /tmp/urdu-rtl-custom.css << EOF
/* ===========================================
   Urdu RTL Styles - Generated by urdu-rtl-styler
   Font: ${PRIMARY_FONT}
   Source: ${FONT_SOURCE}
   =========================================== */

EOF

# Add font import based on source
if [[ "$FONT_SOURCE" == "google" ]]; then
    echo "/* Google Fonts Import */" >> /tmp/urdu-rtl-custom.css
    echo "${GOOGLE_IMPORT}" >> /tmp/urdu-rtl-custom.css
    echo "" >> /tmp/urdu-rtl-custom.css
elif [[ "$FONT_SOURCE" == "local" ]]; then
    mkdir -p static/fonts
    cat >> /tmp/urdu-rtl-custom.css << EOF
/* Local Font - Place font files in static/fonts/ */
@font-face {
  font-family: '${PRIMARY_FONT}';
  src: url('/fonts/${PRIMARY_FONT// /-}-Regular.woff2') format('woff2');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: '${PRIMARY_FONT}';
  src: url('/fonts/${PRIMARY_FONT// /-}-Bold.woff2') format('woff2');
  font-weight: 700;
  font-style: normal;
  font-display: swap;
}

EOF
    log_warning "Local fonts: Place .woff2 files in static/fonts/"
fi

# Add CSS variables and RTL styles with custom values
cat >> /tmp/urdu-rtl-custom.css << EOF
/* CSS Custom Properties */
:root {
  --ifm-font-family-urdu: ${FONT_STACK};
  --ifm-line-height-urdu: ${LINE_HEIGHT};
  --ifm-font-size-urdu-base: 1.1rem;
}

/* RTL Document Base */
[dir='rtl'] {
  font-family: var(--ifm-font-family-urdu);
  line-height: var(--ifm-line-height-urdu);
  text-align: right;
}

/* RTL Typography */
[dir='rtl'] h1, [dir='rtl'] h2, [dir='rtl'] h3,
[dir='rtl'] h4, [dir='rtl'] h5, [dir='rtl'] h6 {
  font-family: var(--ifm-font-family-urdu);
  line-height: 1.8;
}

[dir='rtl'] p, [dir='rtl'] li, [dir='rtl'] td, [dir='rtl'] th {
  font-family: var(--ifm-font-family-urdu);
  font-size: var(--ifm-font-size-urdu-base);
  line-height: var(--ifm-line-height-urdu);
}

/* Navbar RTL */
[dir='rtl'] .navbar__items { flex-direction: row-reverse; }
[dir='rtl'] .navbar__item { margin-right: 0; margin-left: var(--ifm-navbar-item-padding-horizontal); }
[dir='rtl'] .navbar__brand { margin-right: 0; margin-left: 1rem; }
[dir='rtl'] .navbar__toggle { margin-right: 0; margin-left: auto; }
[dir='rtl'] .dropdown__menu { right: auto; left: 0; }
[dir='rtl'] .dropdown__link { text-align: right; }

/* Sidebar RTL */
[dir='rtl'] .theme-doc-sidebar-container {
  border-right: none;
  border-left: 1px solid var(--ifm-toc-border-color);
}
[dir='rtl'] .menu__link {
  padding-right: var(--ifm-menu-link-padding-horizontal);
  padding-left: 0;
}
[dir='rtl'] .menu__caret { transform: rotate(180deg); }
[dir='rtl'] .menu__list .menu__list {
  padding-right: var(--ifm-menu-link-padding-horizontal);
  padding-left: 0;
  margin-right: 0.5rem;
  margin-left: 0;
  border-right: 1px solid var(--ifm-color-emphasis-300);
  border-left: none;
}

/* Breadcrumbs & Pagination RTL */
[dir='rtl'] .breadcrumbs { flex-direction: row-reverse; }
[dir='rtl'] .pagination-nav { flex-direction: row-reverse; }
[dir='rtl'] .pagination-nav__link--prev .pagination-nav__label::before { content: ' →'; }
[dir='rtl'] .pagination-nav__link--next .pagination-nav__label::after { content: '← '; }

/* Table of Contents RTL */
[dir='rtl'] .table-of-contents {
  padding-right: 0;
  padding-left: var(--ifm-toc-padding-horizontal);
  border-right: none;
  border-left: 1px solid var(--ifm-toc-border-color);
}
[dir='rtl'] .table-of-contents__link { text-align: right; }

/* Code Blocks - Keep LTR */
[dir='rtl'] pre, [dir='rtl'] code, [dir='rtl'] .prism-code {
  direction: ltr;
  text-align: left;
  font-family: var(--ifm-font-family-monospace);
}

/* Admonitions RTL */
[dir='rtl'] .admonition {
  border-right: 0.2rem solid var(--ifm-alert-border-color);
  border-left: none;
}
[dir='rtl'] .admonition-icon { margin-right: 0; margin-left: 0.75rem; }

/* Footer RTL */
[dir='rtl'] .footer__links { flex-direction: row-reverse; }
[dir='rtl'] .footer__col, [dir='rtl'] .footer__title { text-align: right; }

/* Lists RTL */
[dir='rtl'] ul, [dir='rtl'] ol { padding-right: 2rem; padding-left: 0; }

/* Blockquotes RTL */
[dir='rtl'] blockquote {
  border-right: 4px solid var(--ifm-color-emphasis-300);
  border-left: none;
  padding-right: 1rem;
  padding-left: 0;
}

/* Search RTL */
[dir='rtl'] .DocSearch-Button { flex-direction: row-reverse; }
EOF

# Append to or create custom.css
if [ -f "src/css/custom.css" ]; then
    echo "" >> src/css/custom.css
    cat /tmp/urdu-rtl-custom.css >> src/css/custom.css
    log_success "Appended RTL styles to src/css/custom.css"
else
    cp /tmp/urdu-rtl-custom.css src/css/custom.css
    log_success "Created src/css/custom.css with RTL styles"
fi

rm /tmp/urdu-rtl-custom.css

# =============================================================================
# 2. Auto-configure docusaurus.config.js (if --auto-config)
# =============================================================================

if [[ "$AUTO_CONFIG" == true ]]; then
    echo ""
    log_info "Auto-configuring docusaurus.config.js..."

    if [ -f "docusaurus.config.js" ]; then
        # Check if i18n config exists
        if grep -q "i18n:" docusaurus.config.js; then
            # Check if ur locale exists
            if grep -q "'ur'" docusaurus.config.js || grep -q '"ur"' docusaurus.config.js; then
                # Check if rtl direction is set
                if grep -q "direction: 'rtl'" docusaurus.config.js; then
                    log_success "RTL already configured for Urdu locale"
                else
                    log_warning "Urdu locale found but RTL not configured"
                    log_info "Please manually add: direction: 'rtl' to ur locale config"
                fi
            else
                log_warning "i18n exists but 'ur' locale not found"
                log_info "Add 'ur' to locales array and configure RTL"
            fi
        else
            # No i18n config - add it
            log_info "Adding i18n configuration..."

            # Create i18n config snippet
            I18N_CONFIG=$(cat << 'CONFIGEOF'

  // i18n configuration (added by urdu-rtl-styler)
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'ur'],
    localeConfigs: {
      en: {
        label: 'English',
        direction: 'ltr',
        htmlLang: 'en-US',
      },
      ur: {
        label: 'اردو',
        direction: 'rtl',
        htmlLang: 'ur-PK',
      },
    },
  },
CONFIGEOF
)
            # Insert after "const config = {" line
            if grep -q "const config = {" docusaurus.config.js; then
                sed -i "/const config = {/a\\${I18N_CONFIG}" docusaurus.config.js
                log_success "Added i18n config to docusaurus.config.js"
            else
                log_warning "Could not find 'const config = {' in docusaurus.config.js"
                log_info "Please manually add i18n configuration"
            fi
        fi
    else
        log_warning "docusaurus.config.js not found"
    fi
fi

# =============================================================================
# 3. Create i18n scaffolding (if --scaffold)
# =============================================================================

if [[ "$SCAFFOLD" == true ]]; then
    echo ""
    log_info "Creating i18n/ur/ scaffolding..."

    # Create directory structure
    mkdir -p i18n/ur/docusaurus-plugin-content-docs/current
    mkdir -p i18n/ur/docusaurus-theme-classic

    # Create navbar.json
    cat > i18n/ur/docusaurus-theme-classic/navbar.json << 'EOF'
{
  "title": {
    "message": "کتاب",
    "description": "The title in the navbar"
  },
  "item.label.Chapters": {
    "message": "ابواب",
    "description": "Navbar item with label Chapters"
  },
  "item.label.GitHub": {
    "message": "گٹ ہب",
    "description": "Navbar item with label GitHub"
  }
}
EOF
    log_success "Created i18n/ur/docusaurus-theme-classic/navbar.json"

    # Create footer.json
    cat > i18n/ur/docusaurus-theme-classic/footer.json << EOF
{
  "copyright": {
    "message": "کاپی رائٹ © $(date +%Y)۔ تمام حقوق محفوظ ہیں۔",
    "description": "The footer copyright"
  }
}
EOF
    log_success "Created i18n/ur/docusaurus-theme-classic/footer.json"

    # Create code.json (UI strings)
    cat > i18n/ur/code.json << 'EOF'
{
  "theme.docs.paginator.previous": {
    "message": "پچھلا",
    "description": "The label used to navigate to the previous doc"
  },
  "theme.docs.paginator.next": {
    "message": "اگلا",
    "description": "The label used to navigate to the next doc"
  },
  "theme.docs.sidebar.expandButtonTitle": {
    "message": "سائیڈبار کھولیں",
    "description": "The ARIA label and title attribute for expand button of doc sidebar"
  },
  "theme.docs.sidebar.collapseButtonTitle": {
    "message": "سائیڈبار بند کریں",
    "description": "The ARIA label and title attribute for collapse button of doc sidebar"
  },
  "theme.colorToggle.ariaLabel": {
    "message": "ڈارک اور لائٹ موڈ کے درمیان تبدیل کریں",
    "description": "The ARIA label for the color mode toggle"
  },
  "theme.docs.breadcrumbs.home": {
    "message": "ہوم",
    "description": "The ARIA label for the home page in the breadcrumbs"
  },
  "theme.NotFound.title": {
    "message": "صفحہ نہیں ملا",
    "description": "The title of the 404 page"
  },
  "theme.NotFound.p1": {
    "message": "ہم وہ نہیں ڈھونڈ سکے جو آپ تلاش کر رہے تھے۔",
    "description": "The first paragraph of the 404 page"
  }
}
EOF
    log_success "Created i18n/ur/code.json"

    # Create sample intro.md
    cat > i18n/ur/docusaurus-plugin-content-docs/current/intro.md << 'EOF'
---
sidebar_position: 1
---

# خوش آمدید

**فزیکل اے آئی کتاب** میں خوش آمدید - روبوٹکس، ROS 2، اور اے آئی سے چلنے والے فزیکل سسٹمز سیکھنے کے لیے آپ کی جامع گائیڈ۔

## آپ کیا سیکھیں گے

| باب | موضوع |
|-----|-------|
| **باب 1** | فزیکل اے آئی اور ROS 2 کا تعارف |
| **باب 2** | Gazebo کے ساتھ سمیولیشن |
| **باب 3** | ویژن-لینگویج-ایکشن ماڈلز |

## شروع کریں

سائیڈبار سے کوئی باب منتخب کریں اور فزیکل اے آئی کی دنیا میں اپنا سفر شروع کریں۔

---

*آخری اپڈیٹ: دسمبر 2025*
EOF
    log_success "Created i18n/ur/docusaurus-plugin-content-docs/current/intro.md"

    # Create chapter placeholders
    for i in 1 2 3; do
        mkdir -p "i18n/ur/docusaurus-plugin-content-docs/current/chapter-$i"
        cat > "i18n/ur/docusaurus-plugin-content-docs/current/chapter-$i/index.md" << EOF
---
sidebar_position: $i
---

# باب $i

یہ باب $i کا اردو ترجمہ ہے۔

## مشمولات

(مواد جلد آ رہا ہے)
EOF
    done
    log_success "Created chapter placeholder files"

    echo ""
    log_info "i18n structure created:"
    echo "   i18n/ur/"
    echo "   ├── code.json"
    echo "   ├── docusaurus-plugin-content-docs/current/"
    echo "   │   ├── intro.md"
    echo "   │   ├── chapter-1/"
    echo "   │   ├── chapter-2/"
    echo "   │   └── chapter-3/"
    echo "   └── docusaurus-theme-classic/"
    echo "       ├── navbar.json"
    echo "       └── footer.json"
fi

# =============================================================================
# Summary
# =============================================================================

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ Urdu RTL Styler setup complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [[ "$AUTO_CONFIG" == false ]]; then
    log_warning "Remember to configure i18n in docusaurus.config.js"
    echo "   Run with --auto-config to do this automatically"
fi

if [[ "$SCAFFOLD" == false ]]; then
    log_warning "i18n/ur/ directory not created"
    echo "   Run with --scaffold to create Urdu content structure"
fi

echo ""
echo "📋 Next steps:"
echo "   1. Test locally: npm run build && npm run serve"
echo "   2. Visit: http://localhost:3000/<repo>/ur/"
echo "   3. Translate content in i18n/ur/"
echo ""
