"""
CORS Middleware Configuration for FastAPI
Allows requests from GitHub Pages frontend to Vercel-hosted API
Generated by vercel-fastapi-link skill
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

def configure_cors(app: FastAPI, github_pages_url: str = None) -> None:
    """
    Configure CORS middleware for FastAPI application.

    Args:
        app: FastAPI application instance
        github_pages_url: Your GitHub Pages URL (e.g., "https://username.github.io")

    Example:
        from cors_middleware import configure_cors

        app = FastAPI()
        configure_cors(app, "https://faiqahm.github.io")
    """

    # Default allowed origins - customize for your deployment
    allowed_origins = [
        "http://localhost:3000",      # Local Docusaurus dev server
        "http://localhost:8000",      # Local FastAPI dev server
        "http://127.0.0.1:3000",
        "http://127.0.0.1:8000",
    ]

    # Add GitHub Pages URL if provided
    if github_pages_url:
        allowed_origins.append(github_pages_url)
        # Also add with and without trailing slash
        allowed_origins.append(github_pages_url.rstrip("/"))
        if not github_pages_url.endswith("/"):
            allowed_origins.append(github_pages_url + "/")

    app.add_middleware(
        CORSMiddleware,
        allow_origins=allowed_origins,
        allow_credentials=True,
        allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
        allow_headers=[
            "Authorization",
            "Content-Type",
            "Accept",
            "Origin",
            "X-Requested-With",
        ],
        expose_headers=["X-Request-ID"],
        max_age=600,  # Cache preflight requests for 10 minutes
    )


# Standalone usage example
if __name__ == "__main__":
    app = FastAPI(title="Example API")
    configure_cors(app, "https://your-username.github.io")

    @app.get("/health")
    def health_check():
        return {"status": "healthy"}
