#!/bin/bash
# =============================================================================
# Vercel FastAPI Link Setup Script
# Configures FastAPI for Vercel deployment with CORS for GitHub Pages
# Version: 1.0.0
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
GITHUB_PAGES_URL="https://faiqahm.github.io"
API_ENTRY="api/main.py"
PROJECT_NAME="Physical AI Book API"
SKIP_VERCEL_JSON=false
SKIP_MAIN=false

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
ASSETS_DIR="$SKILL_DIR/assets"

# =============================================================================
# Functions
# =============================================================================

show_help() {
    cat << EOF
Vercel FastAPI Link - Configure FastAPI for Vercel deployment

Usage: $(basename "$0") [OPTIONS]

Options:
  --github-pages URL     GitHub Pages URL for CORS (default: $GITHUB_PAGES_URL)
  --api-entry PATH       Path to FastAPI main.py (default: $API_ENTRY)
  --project-name NAME    API project name (default: $PROJECT_NAME)
  --skip-vercel-json     Don't create vercel.json
  --skip-main            Don't create main.py template
  -h, --help             Show this help message

Examples:
  $(basename "$0")
  $(basename "$0") --github-pages https://myuser.github.io
  $(basename "$0") --github-pages https://myuser.github.io --project-name "My API"

EOF
}

log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1" >&2
}

# =============================================================================
# Parse Arguments
# =============================================================================

while [[ $# -gt 0 ]]; do
    case $1 in
        --github-pages)
            GITHUB_PAGES_URL="$2"
            shift 2
            ;;
        --api-entry)
            API_ENTRY="$2"
            shift 2
            ;;
        --project-name)
            PROJECT_NAME="$2"
            shift 2
            ;;
        --skip-vercel-json)
            SKIP_VERCEL_JSON=true
            shift
            ;;
        --skip-main)
            SKIP_MAIN=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# =============================================================================
# Main Setup
# =============================================================================

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Vercel FastAPI Link Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
log_info "GitHub Pages URL: $GITHUB_PAGES_URL"
log_info "API Entry: $API_ENTRY"
log_info "Project Name: $PROJECT_NAME"
echo ""

# Get API directory from entry path
API_DIR=$(dirname "$API_ENTRY")

# =============================================================================
# Create vercel.json
# =============================================================================

if [[ "$SKIP_VERCEL_JSON" != true ]]; then
    if [[ -f "vercel.json" ]]; then
        log_warning "vercel.json already exists, backing up to vercel.json.bak"
        cp vercel.json vercel.json.bak
    fi

    cat > vercel.json << EOF
{
  "version": 2,
  "builds": [
    {
      "src": "$API_ENTRY",
      "use": "@vercel/python"
    }
  ],
  "routes": [
    {
      "src": "/api/(.*)",
      "dest": "$API_ENTRY"
    },
    {
      "src": "/health",
      "dest": "$API_ENTRY"
    },
    {
      "src": "/docs",
      "dest": "$API_ENTRY"
    },
    {
      "src": "/openapi.json",
      "dest": "$API_ENTRY"
    }
  ]
}
EOF
    log_success "Created vercel.json"
fi

# =============================================================================
# Create API directory and main.py
# =============================================================================

if [[ "$SKIP_MAIN" != true ]]; then
    # Create API directory
    mkdir -p "$API_DIR"
    log_success "Created $API_DIR/ directory"

    # Create __init__.py
    touch "$API_DIR/__init__.py"

    # Create main.py with CORS configured
    cat > "$API_ENTRY" << EOF
"""
FastAPI Application for Vercel Deployment
Generated by vercel-fastapi-link skill

Project: $PROJECT_NAME
GitHub Pages: $GITHUB_PAGES_URL
"""

import os
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

# =============================================================================
# App Configuration
# =============================================================================

app = FastAPI(
    title="$PROJECT_NAME",
    description="Backend API for the Physical AI Educational Book",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# =============================================================================
# CORS Configuration - Allow GitHub Pages frontend
# =============================================================================

# Get GitHub Pages URL from environment or use default
GITHUB_PAGES_URL = os.getenv("GITHUB_PAGES_URL", "$GITHUB_PAGES_URL")

allowed_origins = [
    "http://localhost:3000",      # Local Docusaurus dev
    "http://localhost:8000",      # Local FastAPI dev
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    GITHUB_PAGES_URL,             # Production GitHub Pages
    f"{GITHUB_PAGES_URL}/",       # With trailing slash
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
    allow_headers=["Authorization", "Content-Type", "Accept", "Origin"],
    max_age=600,
)

# =============================================================================
# Health Check Endpoint
# =============================================================================

@app.get("/health")
async def health_check():
    """Health check endpoint for monitoring."""
    return {"status": "healthy", "service": "physical-ai-book-api"}


@app.get("/")
async def root():
    """Root endpoint with API info."""
    return {
        "message": "$PROJECT_NAME",
        "docs": "/docs",
        "health": "/health",
    }

# =============================================================================
# API Routes - Add your endpoints below
# =============================================================================

@app.get("/api/v1/chapters")
async def list_chapters():
    """List all available chapters."""
    return {
        "chapters": [
            {"id": 1, "title": "Introduction to Physical AI", "slug": "intro"},
            {"id": 2, "title": "Sensors and Perception", "slug": "chapter-1"},
            {"id": 3, "title": "Actuators and Control", "slug": "chapter-2"},
        ]
    }


@app.get("/api/v1/chapters/{chapter_id}")
async def get_chapter(chapter_id: int):
    """Get a specific chapter by ID."""
    chapters = {
        1: {"id": 1, "title": "Introduction to Physical AI", "content": "..."},
        2: {"id": 2, "title": "Sensors and Perception", "content": "..."},
        3: {"id": 3, "title": "Actuators and Control", "content": "..."},
    }
    if chapter_id not in chapters:
        return JSONResponse(status_code=404, content={"detail": "Chapter not found"})
    return chapters[chapter_id]


# =============================================================================
# Error Handlers
# =============================================================================

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """Global exception handler for unhandled errors."""
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error", "type": type(exc).__name__},
    )


# =============================================================================
# Vercel Serverless Handler
# =============================================================================

# The app object is automatically detected by @vercel/python
# No additional handler needed for Vercel deployment
EOF
    log_success "Created $API_ENTRY with CORS middleware"
fi

# =============================================================================
# Create requirements.txt if not exists
# =============================================================================

if [[ ! -f "requirements.txt" ]]; then
    cat > requirements.txt << EOF
# FastAPI and dependencies
fastapi>=0.100.0
uvicorn>=0.23.0

# Optional: Add more dependencies as needed
# pydantic>=2.0.0
# python-dotenv>=1.0.0
EOF
    log_success "Created requirements.txt"
else
    # Check if fastapi is in requirements.txt
    if ! grep -q "fastapi" requirements.txt; then
        echo "" >> requirements.txt
        echo "# FastAPI (added by vercel-fastapi-link)" >> requirements.txt
        echo "fastapi>=0.100.0" >> requirements.txt
        echo "uvicorn>=0.23.0" >> requirements.txt
        log_success "Added fastapi to requirements.txt"
    else
        log_info "fastapi already in requirements.txt"
    fi
fi

# =============================================================================
# Summary
# =============================================================================

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ Vercel FastAPI Link setup complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📁 Files created:"
if [[ "$SKIP_VERCEL_JSON" != true ]]; then
echo "   ├── vercel.json"
fi
if [[ "$SKIP_MAIN" != true ]]; then
echo "   ├── $API_DIR/"
echo "   │   ├── __init__.py"
echo "   │   └── main.py"
fi
echo "   └── requirements.txt"
echo ""
echo "📋 Next steps:"
echo "   1. Install dependencies:"
echo "      pip install -r requirements.txt"
echo ""
echo "   2. Test locally:"
echo "      uvicorn ${API_ENTRY%.py}:app --reload --port 8000"
echo "      curl http://localhost:8000/health"
echo ""
echo "   3. Deploy to Vercel:"
echo "      vercel"
echo ""
echo "   4. Set environment variable (optional):"
echo "      vercel env add GITHUB_PAGES_URL"
echo ""
echo "🔗 CORS configured for:"
echo "   • http://localhost:3000 (local dev)"
echo "   • http://localhost:8000 (local API)"
echo "   • $GITHUB_PAGES_URL (production)"
echo ""
